[book]
authors = ["The Funkin' Crew Inc.", "EliteMasterEric"]
language = "es"
multilingual = true
src = "src"
title = "Documentación de Modding de Friday Night Funkin'"


[output.html]
git-repository-url = "https://github.com/NeonExplorerOficial/funkin-modding-docs"
edit-url-template = "https://github.com/NeonExplorerOficial/funkin-modding-docs/edit/main/{path}"
